server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/network?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  activemq:
    broker-url: "tcp://localhost:61616"
    user: "admin"
    password: "admin"
  jms:
    template:
      default-destination: "queue"

